create table users (
    id bigint generated by default as identity primary key,
    name varchar(120) not null,
    email varchar(160) not null,
    password_hash varchar(255) not null,
    active boolean not null default true,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_users_email unique (email)
);

create index idx_users_active on users (active);
